// AUTO-GENERATED by scripts/build-trophy-assets.mjs — do not edit by hand.
// Custom flat-vector trophy illustrations for honour axis chips.
// Regenerate with: npm run assets:trophies
/* eslint-disable */
export const TROPHY_IMAGES: Record<string, number> = {
  'world-cup': require('./trophies/world-cup.png'),
  'champions-league': require('./trophies/champions-league.png'),
  'europa-league': require('./trophies/europa-league.png'),
  'european-championship': require('./trophies/european-championship.png'),
  'copa-america': require('./trophies/copa-america.png'),
  'ballon-dor': require('./trophies/ballon-dor.png'),
  'golden-boot': require('./trophies/golden-boot.png'),
  'league-title': require('./trophies/league-title.png'),
  'domestic-cup': require('./trophies/domestic-cup.png'),
  'player-of-the-season': require('./trophies/player-of-the-season.png'),
};
