// AUTO-GENERATED by scripts/build-criteria-assets.mjs — do not edit by hand.
// Custom flat-vector illustrations for the non-honour axis chips.
// Regenerate with: npm run assets:criteria
/* eslint-disable */
export const CRITERION_IMAGES: Record<string, number> = {
  'top-leagues': require('./criteria/top-leagues.png'),
  'shirt-number': require('./criteria/shirt-number.png'),
  'teammate': require('./criteria/teammate.png'),
  'position-gk': require('./criteria/position-gk.png'),
  'position-df': require('./criteria/position-df.png'),
  'position-mf': require('./criteria/position-mf.png'),
  'position-fw': require('./criteria/position-fw.png'),
  'tag-current-stars': require('./criteria/tag-current-stars.png'),
  'tag-notable': require('./criteria/tag-notable.png'),
};
