/**
 * Top Bins curated lists. Each list is a hand-authored real-world top 10 —
 * answers are matched against each entry's alias table, NOT the footballer
 * dataset, so retired legends (Gento, Puskás, Piola…) are fair game even when
 * they are not in FOOTBALLERS. `footballerId` only decorates a revealed slot
 * with flag art when the player happens to exist in the dataset.
 *
 * List titles are translatable and live under `tenball.lists.<id>.title` in
 * the i18n catalogs; an OTA content pack ships new lists together with their
 * title strings (same model as the Red Card question pool).
 *
 * Curation rules (enforced by __tests__/lists.test.ts where possible):
 * - exactly 10 entries, ranks 1..10; real-world ties get a curator order.
 * - aliases are pre-folded (lowercase, accents stripped) and unique across
 *   the whole list; bare surname always included unless ambiguous in-list.
 * - values are display strings; '+' marks a still-active, still-counting stat.
 * - prefer closed/historical lists; active-player values go stale and need an
 *   OTA republish to refresh.
 */
import type {TenballList} from './types';

export const BUNDLED_LISTS: TenballList[] = [
  {
    id: 'most-ballon-dor',
    entries: [
      {rank: 1, name: 'Lionel Messi', value: '8', aliases: ['messi', 'lionel messi', 'leo messi'], footballerId: 'Messi, Lionel'},
      {rank: 2, name: 'Cristiano Ronaldo', value: '5', aliases: ['cristiano ronaldo', 'cristiano', 'cr7'], footballerId: 'Ronaldo, Cristiano'},
      {rank: 3, name: 'Michel Platini', value: '3', aliases: ['platini', 'michel platini'], footballerId: 'Platini, Michel'},
      {rank: 4, name: 'Johan Cruyff', value: '3', aliases: ['cruyff', 'johan cruyff', 'cruijff', 'johan cruijff'], footballerId: 'Cruyff, Johan'},
      {rank: 5, name: 'Marco van Basten', value: '3', aliases: ['van basten', 'marco van basten', 'basten'], footballerId: 'van Basten, Marco'},
      {rank: 6, name: 'Franz Beckenbauer', value: '2', aliases: ['beckenbauer', 'franz beckenbauer', 'der kaiser'], footballerId: 'Beckenbauer, Franz'},
      {rank: 7, name: 'Ronaldo Nazário', value: '2', aliases: ['ronaldo nazario', 'r9', 'il fenomeno', 'el fenomeno', 'ronaldo fenomeno'], footballerId: 'Ronaldo'},
      {rank: 8, name: 'Alfredo Di Stéfano', value: '2', aliases: ['di stefano', 'alfredo di stefano', 'distefano'], footballerId: 'Di Stéfano, Alfredo'},
      {rank: 9, name: 'Karl-Heinz Rummenigge', value: '2', aliases: ['rummenigge', 'karl-heinz rummenigge', 'karl heinz rummenigge'], footballerId: 'Rummenigge, Karl-Heinz'},
      {rank: 10, name: 'Kevin Keegan', value: '2', aliases: ['keegan', 'kevin keegan'], footballerId: 'Keegan, Kevin'},
    ],
  },
  {
    id: 'wc-top-scorers',
    entries: [
      {rank: 1, name: 'Miroslav Klose', value: '16', aliases: ['klose', 'miroslav klose'], footballerId: 'Klose, Miroslav'},
      {rank: 2, name: 'Ronaldo Nazário', value: '15', aliases: ['ronaldo', 'ronaldo nazario', 'r9', 'il fenomeno', 'el fenomeno'], footballerId: 'Ronaldo'},
      {rank: 3, name: 'Gerd Müller', value: '14', aliases: ['gerd muller', 'gerd mueller', 'gerd', 'der bomber'], footballerId: 'Müller, Gerd'},
      {rank: 4, name: 'Just Fontaine', value: '13', aliases: ['fontaine', 'just fontaine'], footballerId: 'Fontaine, Just'},
      {rank: 5, name: 'Lionel Messi', value: '13', aliases: ['messi', 'lionel messi', 'leo messi'], footballerId: 'Messi, Lionel'},
      {rank: 6, name: 'Kylian Mbappé', value: '12+', aliases: ['mbappe', 'kylian mbappe'], footballerId: 'Mbappé, Kylian'},
      {rank: 7, name: 'Pelé', value: '12', aliases: ['pele'], footballerId: 'Pelé'},
      {rank: 8, name: 'Sándor Kocsis', value: '11', aliases: ['kocsis', 'sandor kocsis'], footballerId: 'Kocsis, Sándor'},
      {rank: 9, name: 'Jürgen Klinsmann', value: '11', aliases: ['klinsmann', 'jurgen klinsmann'], footballerId: 'Klinsmann, Jürgen'},
      {rank: 10, name: 'Thomas Müller', value: '10', aliases: ['thomas muller', 'thomas mueller'], footballerId: 'Müller, Thomas'},
    ],
  },
  {
    id: 'wc-most-matches',
    entries: [
      {rank: 1, name: 'Lionel Messi', value: '26', aliases: ['messi', 'lionel messi', 'leo messi'], footballerId: 'Messi, Lionel'},
      {rank: 2, name: 'Lothar Matthäus', value: '25', aliases: ['matthaus', 'matthaeus', 'lothar matthaus'], footballerId: 'Matthäus, Lothar'},
      {rank: 3, name: 'Miroslav Klose', value: '24', aliases: ['klose', 'miroslav klose'], footballerId: 'Klose, Miroslav'},
      {rank: 4, name: 'Paolo Maldini', value: '23', aliases: ['maldini', 'paolo maldini'], footballerId: 'Maldini, Paolo'},
      {rank: 5, name: 'Cristiano Ronaldo', value: '22', aliases: ['cristiano ronaldo', 'cristiano', 'cr7', 'ronaldo'], footballerId: 'Ronaldo, Cristiano'},
      {rank: 6, name: 'Diego Maradona', value: '21', aliases: ['maradona', 'diego maradona'], footballerId: 'Maradona, Diego'},
      {rank: 7, name: 'Uwe Seeler', value: '21', aliases: ['seeler', 'uwe seeler'], footballerId: 'Seeler, Uwe'},
      {rank: 8, name: 'Władysław Żmuda', value: '21', aliases: ['zmuda', 'wladyslaw zmuda'], footballerId: 'Żmuda, Władysław'},
      {rank: 9, name: 'Cafu', value: '20', aliases: ['cafu'], footballerId: 'Cafu'},
      {rank: 10, name: 'Philipp Lahm', value: '20', aliases: ['lahm', 'philipp lahm'], footballerId: 'Lahm, Philipp'},
    ],
  },
  {
    id: 'pl-top-scorers',
    entries: [
      {rank: 1, name: 'Alan Shearer', value: '260', aliases: ['shearer', 'alan shearer'], footballerId: 'Shearer, Alan'},
      {rank: 2, name: 'Harry Kane', value: '213', aliases: ['kane', 'harry kane'], footballerId: 'Kane, Harry'},
      {rank: 3, name: 'Wayne Rooney', value: '208', aliases: ['rooney', 'wayne rooney'], footballerId: 'Rooney, Wayne'},
      {rank: 4, name: 'Mohamed Salah', value: '190+', aliases: ['salah', 'mohamed salah', 'mo salah'], footballerId: 'Salah, Mohamed'},
      {rank: 5, name: 'Andy Cole', value: '187', aliases: ['cole', 'andy cole', 'andrew cole'], footballerId: 'Cole, Andy'},
      {rank: 6, name: 'Sergio Agüero', value: '184', aliases: ['aguero', 'sergio aguero', 'kun aguero', 'kun'], footballerId: 'Agüero, Sergio'},
      {rank: 7, name: 'Frank Lampard', value: '177', aliases: ['lampard', 'frank lampard'], footballerId: 'Lampard, Frank'},
      {rank: 8, name: 'Thierry Henry', value: '175', aliases: ['henry', 'thierry henry'], footballerId: 'Henry, Thierry'},
      {rank: 9, name: 'Robbie Fowler', value: '163', aliases: ['fowler', 'robbie fowler'], footballerId: 'Fowler, Robbie'},
      {rank: 10, name: 'Jermain Defoe', value: '162', aliases: ['defoe', 'jermain defoe'], footballerId: 'Defoe, Jermain'},
    ],
  },
  {
    id: 'pl-most-appearances',
    entries: [
      {rank: 1, name: 'Gareth Barry', value: '653', aliases: ['barry', 'gareth barry'], footballerId: 'Barry, Gareth'},
      {rank: 2, name: 'James Milner', value: '638+', aliases: ['milner', 'james milner'], footballerId: 'Milner, James'},
      {rank: 3, name: 'Ryan Giggs', value: '632', aliases: ['giggs', 'ryan giggs'], footballerId: 'Giggs, Ryan'},
      {rank: 4, name: 'Frank Lampard', value: '609', aliases: ['lampard', 'frank lampard'], footballerId: 'Lampard, Frank'},
      {rank: 5, name: 'David James', value: '572', aliases: ['james', 'david james'], footballerId: 'James, David'},
      {rank: 6, name: 'Gary Speed', value: '535', aliases: ['speed', 'gary speed'], footballerId: 'Speed, Gary'},
      {rank: 7, name: 'Emile Heskey', value: '516', aliases: ['heskey', 'emile heskey'], footballerId: 'Heskey, Emile'},
      {rank: 8, name: 'Mark Schwarzer', value: '514', aliases: ['schwarzer', 'mark schwarzer'], footballerId: 'Schwarzer, Mark'},
      {rank: 9, name: 'Jamie Carragher', value: '508', aliases: ['carragher', 'jamie carragher'], footballerId: 'Carragher, Jamie'},
      {rank: 10, name: 'Phil Neville', value: '505', aliases: ['phil neville'], footballerId: 'Neville, Phil'},
    ],
  },
  {
    id: 'pl-most-assists',
    entries: [
      {rank: 1, name: 'Ryan Giggs', value: '162', aliases: ['giggs', 'ryan giggs'], footballerId: 'Giggs, Ryan'},
      {rank: 2, name: 'Kevin De Bruyne', value: '119', aliases: ['de bruyne', 'kevin de bruyne', 'debruyne', 'kdb'], footballerId: 'De Bruyne, Kevin'},
      {rank: 3, name: 'Cesc Fàbregas', value: '111', aliases: ['fabregas', 'cesc fabregas', 'cesc'], footballerId: 'Fàbregas, Cesc'},
      {rank: 4, name: 'Wayne Rooney', value: '103', aliases: ['rooney', 'wayne rooney'], footballerId: 'Rooney, Wayne'},
      {rank: 5, name: 'Frank Lampard', value: '102', aliases: ['lampard', 'frank lampard'], footballerId: 'Lampard, Frank'},
      {rank: 6, name: 'David Silva', value: '93', aliases: ['silva', 'david silva'], footballerId: 'Silva, David'},
      {rank: 7, name: 'Steven Gerrard', value: '92', aliases: ['gerrard', 'steven gerrard'], footballerId: 'Gerrard, Steven'},
      {rank: 8, name: 'James Milner', value: '91', aliases: ['milner', 'james milner'], footballerId: 'Milner, James'},
      {rank: 9, name: 'Mohamed Salah', value: '86+', aliases: ['salah', 'mohamed salah', 'mo salah'], footballerId: 'Salah, Mohamed'},
      {rank: 10, name: 'David Beckham', value: '80', aliases: ['beckham', 'david beckham'], footballerId: 'Beckham, David'},
    ],
  },
  {
    id: 'ucl-top-scorers',
    entries: [
      {rank: 1, name: 'Cristiano Ronaldo', value: '140', aliases: ['cristiano ronaldo', 'cristiano', 'cr7', 'ronaldo'], footballerId: 'Ronaldo, Cristiano'},
      {rank: 2, name: 'Lionel Messi', value: '129', aliases: ['messi', 'lionel messi', 'leo messi'], footballerId: 'Messi, Lionel'},
      {rank: 3, name: 'Robert Lewandowski', value: '105+', aliases: ['lewandowski', 'robert lewandowski', 'lewa'], footballerId: 'Lewandowski, Robert'},
      {rank: 4, name: 'Karim Benzema', value: '90', aliases: ['benzema', 'karim benzema'], footballerId: 'Benzema, Karim'},
      {rank: 5, name: 'Raúl', value: '71', aliases: ['raul', 'raul gonzalez'], footballerId: 'Raúl'},
      {rank: 6, name: 'Kylian Mbappé', value: '60+', aliases: ['mbappe', 'kylian mbappe'], footballerId: 'Mbappé, Kylian'},
      {rank: 7, name: 'Thomas Müller', value: '57', aliases: ['muller', 'mueller', 'thomas muller', 'thomas mueller'], footballerId: 'Müller, Thomas'},
      {rank: 8, name: 'Ruud van Nistelrooy', value: '56', aliases: ['van nistelrooy', 'nistelrooy', 'ruud van nistelrooy', 'ruud'], footballerId: 'van Nistelrooy, Ruud'},
      {rank: 9, name: 'Erling Haaland', value: '52+', aliases: ['haaland', 'erling haaland'], footballerId: 'Haaland, Erling'},
      {rank: 10, name: 'Thierry Henry', value: '50', aliases: ['henry', 'thierry henry'], footballerId: 'Henry, Thierry'},
    ],
  },
  {
    id: 'record-transfers',
    entries: [
      {rank: 1, name: 'Neymar', value: '€222m', aliases: ['neymar', 'neymar jr'], footballerId: 'Neymar'},
      {rank: 2, name: 'Kylian Mbappé', value: '€180m', aliases: ['mbappe', 'kylian mbappe'], footballerId: 'Mbappé, Kylian'},
      {rank: 3, name: 'Philippe Coutinho', value: '€145m', aliases: ['coutinho', 'philippe coutinho'], footballerId: 'Coutinho, Philippe'},
      {rank: 4, name: 'Alexander Isak', value: '€144m', aliases: ['isak', 'alexander isak'], footballerId: 'Isak, Alexander'},
      {rank: 5, name: 'Ousmane Dembélé', value: '€135m', aliases: ['dembele', 'ousmane dembele'], footballerId: 'Dembélé, Ousmane'},
      {rank: 6, name: 'João Félix', value: '€127m', aliases: ['joao felix', 'felix'], footballerId: 'Félix, João'},
      {rank: 7, name: 'Florian Wirtz', value: '€125m', aliases: ['wirtz', 'florian wirtz'], footballerId: 'Wirtz, Florian'},
      {rank: 8, name: 'Enzo Fernández', value: '€121m', aliases: ['enzo fernandez', 'enzo', 'fernandez'], footballerId: 'Fernández, Enzo'},
      {rank: 9, name: 'Antoine Griezmann', value: '€120m', aliases: ['griezmann', 'antoine griezmann'], footballerId: 'Griezmann, Antoine'},
      {rank: 10, name: 'Jack Grealish', value: '€117m', aliases: ['grealish', 'jack grealish'], footballerId: 'Grealish, Jack'},
    ],
  },
  {
    id: 'intl-goals-men',
    entries: [
      {rank: 1, name: 'Cristiano Ronaldo', value: '140+', aliases: ['cristiano ronaldo', 'cristiano', 'cr7', 'ronaldo'], footballerId: 'Ronaldo, Cristiano'},
      {rank: 2, name: 'Lionel Messi', value: '112+', aliases: ['messi', 'lionel messi', 'leo messi'], footballerId: 'Messi, Lionel'},
      {rank: 3, name: 'Ali Daei', value: '108', aliases: ['daei', 'ali daei'], footballerId: 'Daei, Ali'},
      {rank: 4, name: 'Sunil Chhetri', value: '94+', aliases: ['chhetri', 'sunil chhetri']},
      {rank: 5, name: 'Mokhtar Dahari', value: '89', aliases: ['dahari', 'mokhtar dahari']},
      {rank: 6, name: 'Ali Mabkhout', value: '85+', aliases: ['mabkhout', 'ali mabkhout']},
      {rank: 7, name: 'Ferenc Puskás', value: '84', aliases: ['puskas', 'ferenc puskas'], footballerId: 'Puskás, Ferenc'},
      {rank: 8, name: 'Neymar', value: '79', aliases: ['neymar', 'neymar jr'], footballerId: 'Neymar'},
      {rank: 9, name: 'Hussein Saeed', value: '78', aliases: ['hussein saeed', 'saeed']},
      {rank: 10, name: 'Pelé', value: '77', aliases: ['pele'], footballerId: 'Pelé'},
    ],
  },
  {
    id: 'serie-a-top-scorers',
    entries: [
      {rank: 1, name: 'Silvio Piola', value: '274', aliases: ['piola', 'silvio piola'], footballerId: 'Piola, Silvio'},
      {rank: 2, name: 'Francesco Totti', value: '250', aliases: ['totti', 'francesco totti'], footballerId: 'Totti, Francesco'},
      {rank: 3, name: 'Gunnar Nordahl', value: '225', aliases: ['nordahl', 'gunnar nordahl'], footballerId: 'Nordahl, Gunnar'},
      {rank: 4, name: 'Giuseppe Meazza', value: '216', aliases: ['meazza', 'giuseppe meazza'], footballerId: 'Meazza, Giuseppe'},
      {rank: 5, name: 'José Altafini', value: '216', aliases: ['altafini', 'jose altafini'], footballerId: 'Altafini, José'},
      {rank: 6, name: 'Antonio Di Natale', value: '209', aliases: ['di natale', 'antonio di natale', 'dinatale'], footballerId: 'Di Natale, Antonio'},
      {rank: 7, name: 'Roberto Baggio', value: '205', aliases: ['baggio', 'roberto baggio'], footballerId: 'Baggio, Roberto'},
      {rank: 8, name: 'Ciro Immobile', value: '201', aliases: ['immobile', 'ciro immobile'], footballerId: 'Immobile, Ciro'},
      {rank: 9, name: 'Giuseppe Signori', value: '188', aliases: ['signori', 'giuseppe signori', 'beppe signori'], footballerId: 'Signori, Giuseppe'},
      {rank: 10, name: 'Alessandro Del Piero', value: '188', aliases: ['del piero', 'alessandro del piero', 'delpiero'], footballerId: 'Del Piero, Alessandro'},
    ],
  },
  {
    id: 'dk-most-caps',
    entries: [
      {rank: 1, name: 'Christian Eriksen', value: '140+', aliases: ['eriksen', 'christian eriksen'], footballerId: 'Eriksen, Christian'},
      {rank: 2, name: 'Simon Kjær', value: '132', aliases: ['kjaer', 'kjær', 'simon kjaer', 'simon kjær'], footballerId: 'Kjær, Simon'},
      {rank: 3, name: 'Peter Schmeichel', value: '129', aliases: ['peter schmeichel'], footballerId: 'Schmeichel, Peter'},
      {rank: 4, name: 'Dennis Rommedahl', value: '126', aliases: ['rommedahl', 'dennis rommedahl'], footballerId: 'Rommedahl, Dennis'},
      {rank: 5, name: 'Jon Dahl Tomasson', value: '112', aliases: ['tomasson', 'jon dahl tomasson', 'jon dahl'], footballerId: 'Tomasson, Jon Dahl'},
      {rank: 6, name: 'Thomas Helveg', value: '108', aliases: ['helveg', 'thomas helveg'], footballerId: 'Helveg, Thomas'},
      {rank: 7, name: 'Kasper Schmeichel', value: '105+', aliases: ['kasper schmeichel'], footballerId: 'Schmeichel, Kasper'},
      {rank: 8, name: 'Michael Laudrup', value: '104', aliases: ['laudrup', 'michael laudrup'], footballerId: 'Laudrup, Michael'},
      {rank: 9, name: 'Martin Jørgensen', value: '102', aliases: ['jorgensen', 'jørgensen', 'martin jorgensen', 'martin jørgensen'], footballerId: 'Jørgensen, Martin'},
      {rank: 10, name: 'Morten Olsen', value: '102', aliases: ['olsen', 'morten olsen'], footballerId: 'Olsen, Morten'},
    ],
  },
  // ── "Last 10 different …" chronological lists ───────────────────────────
  // Rank 1 = most recent; the value is the (latest) winning year/season.
  // Every answer owns exactly one slot, so repeat winners are deduped — these
  // are the last 10 DIFFERENT winners, and the titles say so.
  {
    id: 'last-10-ballon-dor',
    entries: [
      {rank: 1, name: 'Ousmane Dembélé', value: '2025', aliases: ['dembele', 'ousmane dembele'], footballerId: 'Dembélé, Ousmane'},
      {rank: 2, name: 'Rodri', value: '2024', aliases: ['rodri', 'rodrigo hernandez'], footballerId: 'Rodri'},
      {rank: 3, name: 'Lionel Messi', value: '2023', aliases: ['messi', 'lionel messi', 'leo messi'], footballerId: 'Messi, Lionel'},
      {rank: 4, name: 'Karim Benzema', value: '2022', aliases: ['benzema', 'karim benzema'], footballerId: 'Benzema, Karim'},
      {rank: 5, name: 'Luka Modrić', value: '2018', aliases: ['modric', 'luka modric'], footballerId: 'Modrić, Luka'},
      {rank: 6, name: 'Cristiano Ronaldo', value: '2017', aliases: ['cristiano ronaldo', 'cristiano', 'cr7', 'ronaldo'], footballerId: 'Ronaldo, Cristiano'},
      {rank: 7, name: 'Kaká', value: '2007', aliases: ['kaka', 'ricardo kaka'], footballerId: 'Kaká'},
      {rank: 8, name: 'Fabio Cannavaro', value: '2006', aliases: ['cannavaro', 'fabio cannavaro'], footballerId: 'Cannavaro, Fabio'},
      {rank: 9, name: 'Ronaldinho', value: '2005', aliases: ['ronaldinho', 'ronaldinho gaucho'], footballerId: 'Ronaldinho'},
      {rank: 10, name: 'Andriy Shevchenko', value: '2004', aliases: ['shevchenko', 'andriy shevchenko', 'sheva'], footballerId: 'Shevchenko, Andriy'},
    ],
  },
  {
    id: 'last-10-wc-golden-ball',
    entries: [
      {rank: 1, name: 'Lionel Messi', value: '2022', aliases: ['messi', 'lionel messi', 'leo messi'], footballerId: 'Messi, Lionel'},
      {rank: 2, name: 'Luka Modrić', value: '2018', aliases: ['modric', 'luka modric'], footballerId: 'Modrić, Luka'},
      {rank: 3, name: 'Diego Forlán', value: '2010', aliases: ['forlan', 'diego forlan'], footballerId: 'Forlán, Diego'},
      {rank: 4, name: 'Zinédine Zidane', value: '2006', aliases: ['zidane', 'zinedine zidane', 'zizou'], footballerId: 'Zidane, Zinédine'},
      {rank: 5, name: 'Oliver Kahn', value: '2002', aliases: ['kahn', 'oliver kahn'], footballerId: 'Kahn, Oliver'},
      {rank: 6, name: 'Ronaldo Nazário', value: '1998', aliases: ['ronaldo', 'ronaldo nazario', 'r9', 'il fenomeno', 'el fenomeno'], footballerId: 'Ronaldo'},
      {rank: 7, name: 'Romário', value: '1994', aliases: ['romario'], footballerId: 'Romário'},
      {rank: 8, name: 'Salvatore Schillaci', value: '1990', aliases: ['schillaci', 'salvatore schillaci', 'toto schillaci'], footballerId: 'Schillaci, Salvatore'},
      {rank: 9, name: 'Diego Maradona', value: '1986', aliases: ['maradona', 'diego maradona'], footballerId: 'Maradona, Diego'},
      {rank: 10, name: 'Paolo Rossi', value: '1982', aliases: ['paolo rossi', 'rossi'], footballerId: 'Rossi, Paolo'},
    ],
  },
  {
    id: 'last-10-wc-golden-boot',
    entries: [
      {rank: 1, name: 'Kylian Mbappé', value: '2022 (8)', aliases: ['mbappe', 'kylian mbappe'], footballerId: 'Mbappé, Kylian'},
      {rank: 2, name: 'Harry Kane', value: '2018 (6)', aliases: ['kane', 'harry kane'], footballerId: 'Kane, Harry'},
      {rank: 3, name: 'James Rodríguez', value: '2014 (6)', aliases: ['james rodriguez', 'james'], footballerId: 'Rodríguez, James'},
      {rank: 4, name: 'Thomas Müller', value: '2010 (5)', aliases: ['muller', 'mueller', 'thomas muller', 'thomas mueller'], footballerId: 'Müller, Thomas'},
      {rank: 5, name: 'Miroslav Klose', value: '2006 (5)', aliases: ['klose', 'miroslav klose'], footballerId: 'Klose, Miroslav'},
      {rank: 6, name: 'Ronaldo Nazário', value: '2002 (8)', aliases: ['ronaldo', 'ronaldo nazario', 'r9', 'il fenomeno', 'el fenomeno'], footballerId: 'Ronaldo'},
      {rank: 7, name: 'Davor Šuker', value: '1998 (6)', aliases: ['suker', 'davor suker'], footballerId: 'Šuker, Davor'},
      {rank: 8, name: 'Hristo Stoichkov & Oleg Salenko', value: '1994 (6)', aliases: ['stoichkov', 'hristo stoichkov', 'salenko', 'oleg salenko']},
      {rank: 9, name: 'Salvatore Schillaci', value: '1990 (6)', aliases: ['schillaci', 'salvatore schillaci', 'toto schillaci'], footballerId: 'Schillaci, Salvatore'},
      {rank: 10, name: 'Gary Lineker', value: '1986 (6)', aliases: ['lineker', 'gary lineker'], footballerId: 'Lineker, Gary'},
    ],
  },
  {
    id: 'last-10-cl-winners',
    entries: [
      {rank: 1, name: 'Paris Saint-Germain', value: '2026', aliases: ['psg', 'paris saint-germain', 'paris saint germain', 'paris sg', 'paris']},
      {rank: 2, name: 'Real Madrid', value: '2024', aliases: ['real madrid', 'real', 'madrid']},
      {rank: 3, name: 'Manchester City', value: '2023', aliases: ['man city', 'manchester city', 'city']},
      {rank: 4, name: 'Chelsea', value: '2021', aliases: ['chelsea']},
      {rank: 5, name: 'Bayern Munich', value: '2020', aliases: ['bayern', 'bayern munich', 'bayern munchen', 'fc bayern']},
      {rank: 6, name: 'Liverpool', value: '2019', aliases: ['liverpool', 'lfc']},
      {rank: 7, name: 'Barcelona', value: '2015', aliases: ['barcelona', 'barca', 'fc barcelona']},
      {rank: 8, name: 'Inter', value: '2010', aliases: ['inter', 'inter milan', 'internazionale']},
      {rank: 9, name: 'Manchester United', value: '2008', aliases: ['man united', 'manchester united', 'united', 'man utd']},
      {rank: 10, name: 'AC Milan', value: '2007', aliases: ['milan', 'ac milan']},
    ],
  },
  {
    id: 'last-10-cl-managers',
    entries: [
      {rank: 1, name: 'Luis Enrique', value: '2026', aliases: ['luis enrique', 'enrique']},
      {rank: 2, name: 'Carlo Ancelotti', value: '2024', aliases: ['ancelotti', 'carlo ancelotti']},
      {rank: 3, name: 'Pep Guardiola', value: '2023', aliases: ['guardiola', 'pep guardiola', 'pep']},
      {rank: 4, name: 'Thomas Tuchel', value: '2021', aliases: ['tuchel', 'thomas tuchel']},
      {rank: 5, name: 'Hansi Flick', value: '2020', aliases: ['flick', 'hansi flick']},
      {rank: 6, name: 'Jürgen Klopp', value: '2019', aliases: ['klopp', 'jurgen klopp']},
      {rank: 7, name: 'Zinédine Zidane', value: '2018', aliases: ['zidane', 'zinedine zidane', 'zizou']},
      {rank: 8, name: 'Jupp Heynckes', value: '2013', aliases: ['heynckes', 'jupp heynckes']},
      {rank: 9, name: 'Roberto Di Matteo', value: '2012', aliases: ['di matteo', 'roberto di matteo', 'dimatteo']},
      {rank: 10, name: 'José Mourinho', value: '2010', aliases: ['mourinho', 'jose mourinho']},
    ],
  },
  {
    id: 'last-10-europa-winners',
    entries: [
      {rank: 1, name: 'Aston Villa', value: '2026', aliases: ['aston villa', 'villa']},
      {rank: 2, name: 'Tottenham Hotspur', value: '2025', aliases: ['tottenham', 'spurs', 'tottenham hotspur']},
      {rank: 3, name: 'Atalanta', value: '2024', aliases: ['atalanta']},
      {rank: 4, name: 'Sevilla', value: '2023', aliases: ['sevilla', 'fc sevilla']},
      {rank: 5, name: 'Eintracht Frankfurt', value: '2022', aliases: ['eintracht frankfurt', 'frankfurt', 'eintracht']},
      {rank: 6, name: 'Villarreal', value: '2021', aliases: ['villarreal']},
      {rank: 7, name: 'Chelsea', value: '2019', aliases: ['chelsea']},
      {rank: 8, name: 'Atlético Madrid', value: '2018', aliases: ['atletico', 'atletico madrid', 'atleti']},
      {rank: 9, name: 'Manchester United', value: '2017', aliases: ['man united', 'manchester united', 'united', 'man utd']},
      {rank: 10, name: 'Porto', value: '2011', aliases: ['porto', 'fc porto']},
    ],
  },
  {
    id: 'last-10-fa-cup-winners',
    entries: [
      {rank: 1, name: 'Manchester City', value: '2026', aliases: ['man city', 'manchester city', 'city']},
      {rank: 2, name: 'Crystal Palace', value: '2025', aliases: ['crystal palace', 'palace']},
      {rank: 3, name: 'Manchester United', value: '2024', aliases: ['man united', 'manchester united', 'united', 'man utd']},
      {rank: 4, name: 'Liverpool', value: '2022', aliases: ['liverpool', 'lfc']},
      {rank: 5, name: 'Leicester City', value: '2021', aliases: ['leicester', 'leicester city']},
      {rank: 6, name: 'Arsenal', value: '2020', aliases: ['arsenal']},
      {rank: 7, name: 'Chelsea', value: '2018', aliases: ['chelsea']},
      {rank: 8, name: 'Wigan Athletic', value: '2013', aliases: ['wigan', 'wigan athletic']},
      {rank: 9, name: 'Portsmouth', value: '2008', aliases: ['portsmouth', 'pompey']},
      {rank: 10, name: 'Everton', value: '1995', aliases: ['everton']},
    ],
  },
  {
    id: 'last-10-english-champions',
    entries: [
      {rank: 1, name: 'Arsenal', value: '2025/26', aliases: ['arsenal']},
      {rank: 2, name: 'Liverpool', value: '2024/25', aliases: ['liverpool', 'lfc']},
      {rank: 3, name: 'Manchester City', value: '2023/24', aliases: ['man city', 'manchester city', 'city']},
      {rank: 4, name: 'Chelsea', value: '2016/17', aliases: ['chelsea']},
      {rank: 5, name: 'Leicester City', value: '2015/16', aliases: ['leicester', 'leicester city']},
      {rank: 6, name: 'Manchester United', value: '2012/13', aliases: ['man united', 'manchester united', 'united', 'man utd']},
      {rank: 7, name: 'Blackburn Rovers', value: '1994/95', aliases: ['blackburn', 'blackburn rovers']},
      {rank: 8, name: 'Leeds United', value: '1991/92', aliases: ['leeds', 'leeds united']},
      {rank: 9, name: 'Everton', value: '1986/87', aliases: ['everton']},
      {rank: 10, name: 'Aston Villa', value: '1980/81', aliases: ['aston villa', 'villa']},
    ],
  },
  {
    id: 'last-10-pl-managers',
    entries: [
      {rank: 1, name: 'Mikel Arteta', value: '2025/26', aliases: ['arteta', 'mikel arteta']},
      {rank: 2, name: 'Arne Slot', value: '2024/25', aliases: ['slot', 'arne slot']},
      {rank: 3, name: 'Pep Guardiola', value: '2023/24', aliases: ['guardiola', 'pep guardiola', 'pep']},
      {rank: 4, name: 'Jürgen Klopp', value: '2019/20', aliases: ['klopp', 'jurgen klopp']},
      {rank: 5, name: 'Antonio Conte', value: '2016/17', aliases: ['conte', 'antonio conte']},
      {rank: 6, name: 'Claudio Ranieri', value: '2015/16', aliases: ['ranieri', 'claudio ranieri']},
      {rank: 7, name: 'José Mourinho', value: '2014/15', aliases: ['mourinho', 'jose mourinho']},
      {rank: 8, name: 'Manuel Pellegrini', value: '2013/14', aliases: ['pellegrini', 'manuel pellegrini']},
      {rank: 9, name: 'Sir Alex Ferguson', value: '2012/13', aliases: ['ferguson', 'alex ferguson', 'sir alex ferguson', 'sir alex', 'fergie']},
      {rank: 10, name: 'Roberto Mancini', value: '2011/12', aliases: ['mancini', 'roberto mancini']},
    ],
  },
  {
    id: 'last-10-serie-a-champions',
    entries: [
      {rank: 1, name: 'Inter', value: '2025/26', aliases: ['inter', 'inter milan', 'internazionale']},
      {rank: 2, name: 'Napoli', value: '2024/25', aliases: ['napoli']},
      {rank: 3, name: 'AC Milan', value: '2021/22', aliases: ['milan', 'ac milan']},
      {rank: 4, name: 'Juventus', value: '2019/20', aliases: ['juventus', 'juve']},
      {rank: 5, name: 'Roma', value: '2000/01', aliases: ['roma', 'as roma']},
      {rank: 6, name: 'Lazio', value: '1999/00', aliases: ['lazio']},
      {rank: 7, name: 'Sampdoria', value: '1990/91', aliases: ['sampdoria', 'samp']},
      {rank: 8, name: 'Hellas Verona', value: '1984/85', aliases: ['verona', 'hellas verona', 'hellas']},
      {rank: 9, name: 'Torino', value: '1975/76', aliases: ['torino']},
      {rank: 10, name: 'Cagliari', value: '1969/70', aliases: ['cagliari']},
    ],
  },
  {
    id: 'last-10-pl-golden-boot',
    entries: [
      {rank: 1, name: 'Erling Haaland', value: '2025/26', aliases: ['haaland', 'erling haaland'], footballerId: 'Haaland, Erling'},
      {rank: 2, name: 'Mohamed Salah', value: '2024/25 (29)', aliases: ['salah', 'mohamed salah', 'mo salah'], footballerId: 'Salah, Mohamed'},
      {rank: 3, name: 'Son Heung-min', value: '2021/22 (23)', aliases: ['son', 'son heung-min', 'son heung min', 'heung-min son', 'sonny'], footballerId: 'Son, Heung-min'},
      {rank: 4, name: 'Harry Kane', value: '2020/21 (23)', aliases: ['kane', 'harry kane'], footballerId: 'Kane, Harry'},
      {rank: 5, name: 'Jamie Vardy', value: '2019/20 (23)', aliases: ['vardy', 'jamie vardy'], footballerId: 'Vardy, Jamie'},
      {rank: 6, name: 'Sadio Mané', value: '2018/19 (22)', aliases: ['mane', 'sadio mane'], footballerId: 'Mané, Sadio'},
      {rank: 7, name: 'Pierre-Emerick Aubameyang', value: '2018/19 (22)', aliases: ['aubameyang', 'pierre-emerick aubameyang', 'auba'], footballerId: 'Aubameyang, Pierre-Emerick'},
      {rank: 8, name: 'Sergio Agüero', value: '2014/15 (26)', aliases: ['aguero', 'sergio aguero', 'kun aguero', 'kun'], footballerId: 'Agüero, Sergio'},
      {rank: 9, name: 'Luis Suárez', value: '2013/14 (31)', aliases: ['suarez', 'luis suarez'], footballerId: 'Suárez, Luis'},
      {rank: 10, name: 'Robin van Persie', value: '2012/13 (26)', aliases: ['van persie', 'robin van persie', 'rvp'], footballerId: 'van Persie, Robin'},
    ],
  },
  {
    id: 'last-10-pfa-poty',
    entries: [
      {rank: 1, name: 'Mohamed Salah', value: '2024/25', aliases: ['salah', 'mohamed salah', 'mo salah'], footballerId: 'Salah, Mohamed'},
      {rank: 2, name: 'Phil Foden', value: '2023/24', aliases: ['foden', 'phil foden'], footballerId: 'Foden, Phil'},
      {rank: 3, name: 'Erling Haaland', value: '2022/23', aliases: ['haaland', 'erling haaland'], footballerId: 'Haaland, Erling'},
      {rank: 4, name: 'Kevin De Bruyne', value: '2021/22', aliases: ['de bruyne', 'kevin de bruyne', 'debruyne', 'kdb'], footballerId: 'De Bruyne, Kevin'},
      {rank: 5, name: 'Virgil van Dijk', value: '2018/19', aliases: ['van dijk', 'virgil van dijk', 'virgil'], footballerId: 'van Dijk, Virgil'},
      {rank: 6, name: "N'Golo Kanté", value: '2016/17', aliases: ['kante', 'ngolo kante', "n'golo kante"], footballerId: "Kanté, N'Golo"},
      {rank: 7, name: 'Riyad Mahrez', value: '2015/16', aliases: ['mahrez', 'riyad mahrez'], footballerId: 'Mahrez, Riyad'},
      {rank: 8, name: 'Eden Hazard', value: '2014/15', aliases: ['hazard', 'eden hazard'], footballerId: 'Hazard, Eden'},
      {rank: 9, name: 'Luis Suárez', value: '2013/14', aliases: ['suarez', 'luis suarez'], footballerId: 'Suárez, Luis'},
      {rank: 10, name: 'Gareth Bale', value: '2012/13', aliases: ['bale', 'gareth bale'], footballerId: 'Bale, Gareth'},
    ],
  },
  {
    id: 'last-10-cl-final-cities',
    entries: [
      {rank: 1, name: 'Budapest', value: '2026', aliases: ['budapest', 'puskas arena']},
      {rank: 2, name: 'Munich', value: '2025', aliases: ['munich', 'munchen', 'allianz arena']},
      {rank: 3, name: 'London', value: '2024', aliases: ['london', 'wembley']},
      {rank: 4, name: 'Istanbul', value: '2023', aliases: ['istanbul', 'ataturk']},
      {rank: 5, name: 'Paris', value: '2022', aliases: ['paris', 'stade de france', 'saint-denis']},
      {rank: 6, name: 'Porto', value: '2021', aliases: ['porto', 'estadio do dragao', 'dragao']},
      {rank: 7, name: 'Lisbon', value: '2020', aliases: ['lisbon', 'lissabon', 'lisboa', 'estadio da luz']},
      {rank: 8, name: 'Madrid', value: '2019', aliases: ['madrid', 'metropolitano', 'wanda metropolitano']},
      {rank: 9, name: 'Kyiv', value: '2018', aliases: ['kyiv', 'kiev']},
      {rank: 10, name: 'Cardiff', value: '2017', aliases: ['cardiff', 'millennium stadium', 'principality stadium']},
    ],
  },
  {
    id: 'last-10-superliga-champions',
    entries: [
      {rank: 1, name: 'AGF', value: '2025/26', aliases: ['agf', 'agf aarhus', 'aarhus', 'arhus']},
      {rank: 2, name: 'FC København', value: '2024/25', aliases: ['fck', 'fc kobenhavn', 'fc københavn', 'kobenhavn', 'københavn', 'copenhagen', 'fc copenhagen']},
      {rank: 3, name: 'FC Midtjylland', value: '2023/24', aliases: ['fcm', 'fc midtjylland', 'midtjylland']},
      {rank: 4, name: 'Brøndby IF', value: '2020/21', aliases: ['brondby', 'brøndby', 'brondby if', 'brøndby if', 'bif']},
      {rank: 5, name: 'AaB', value: '2013/14', aliases: ['aab', 'aalborg', 'aab aalborg']},
      {rank: 6, name: 'FC Nordsjælland', value: '2011/12', aliases: ['fcn', 'nordsjælland', 'nordsjaelland', 'fc nordsjælland', 'fc nordsjaelland']},
      {rank: 7, name: 'Herfølge BK', value: '1999/00', aliases: ['herfølge', 'herfolge', 'herfølge bk', 'herfolge bk']},
      {rank: 8, name: 'Silkeborg IF', value: '1993/94', aliases: ['silkeborg', 'silkeborg if']},
      {rank: 9, name: 'Lyngby', value: '1991/92', aliases: ['lyngby', 'lyngby bk']},
      {rank: 10, name: 'OB', value: '1989', aliases: ['ob', 'odense', 'odense boldklub']},
    ],
  },
  {
    id: 'last-10-african-poty',
    entries: [
      {rank: 1, name: 'Achraf Hakimi', value: '2025', aliases: ['hakimi', 'achraf hakimi'], footballerId: 'Hakimi, Achraf'},
      {rank: 2, name: 'Ademola Lookman', value: '2024', aliases: ['lookman', 'ademola lookman'], footballerId: 'Lookman, Ademola'},
      {rank: 3, name: 'Victor Osimhen', value: '2023', aliases: ['osimhen', 'victor osimhen'], footballerId: 'Osimhen, Victor'},
      {rank: 4, name: 'Sadio Mané', value: '2022', aliases: ['mane', 'sadio mane'], footballerId: 'Mané, Sadio'},
      {rank: 5, name: 'Mohamed Salah', value: '2018', aliases: ['salah', 'mohamed salah', 'mo salah'], footballerId: 'Salah, Mohamed'},
      {rank: 6, name: 'Riyad Mahrez', value: '2016', aliases: ['mahrez', 'riyad mahrez'], footballerId: 'Mahrez, Riyad'},
      {rank: 7, name: 'Pierre-Emerick Aubameyang', value: '2015', aliases: ['aubameyang', 'pierre-emerick aubameyang', 'auba'], footballerId: 'Aubameyang, Pierre-Emerick'},
      {rank: 8, name: 'Yaya Touré', value: '2014', aliases: ['yaya toure', 'toure', 'yaya'], footballerId: 'Touré, Yaya'},
      {rank: 9, name: "Samuel Eto'o", value: '2010', aliases: ['etoo', "eto'o", 'samuel etoo', "samuel eto'o"], footballerId: 'Eto\'o, Samuel'},
      {rank: 10, name: 'Didier Drogba', value: '2009', aliases: ['drogba', 'didier drogba'], footballerId: 'Drogba, Didier'},
    ],
  },
  {
    id: 'dk-top-scorers',
    entries: [
      {rank: 1, name: 'Poul "Tist" Nielsen', value: '52', aliases: ['nielsen', 'poul nielsen', 'tist']},
      {rank: 2, name: 'Jon Dahl Tomasson', value: '52', aliases: ['tomasson', 'jon dahl tomasson', 'jon dahl'], footballerId: 'Tomasson, Jon Dahl'},
      {rank: 3, name: 'Christian Eriksen', value: '45+', aliases: ['eriksen', 'christian eriksen'], footballerId: 'Eriksen, Christian'},
      {rank: 4, name: 'Pauli Jørgensen', value: '44', aliases: ['jorgensen', 'jørgensen', 'pauli jorgensen', 'pauli jørgensen']},
      {rank: 5, name: 'Ole Madsen', value: '42', aliases: ['madsen', 'ole madsen']},
      {rank: 6, name: 'Preben Elkjær', value: '38', aliases: ['elkjaer', 'elkjær', 'preben elkjaer', 'preben elkjær'], footballerId: 'Elkjær, Preben'},
      {rank: 7, name: 'Michael Laudrup', value: '37', aliases: ['laudrup', 'michael laudrup'], footballerId: 'Laudrup, Michael'},
      {rank: 8, name: 'Nicklas Bendtner', value: '30', aliases: ['bendtner', 'nicklas bendtner', 'niklas bendtner'], footballerId: 'Bendtner, Niklas'},
      {rank: 9, name: 'Henning Enoksen', value: '29', aliases: ['enoksen', 'henning enoksen']},
      {rank: 10, name: 'Ebbe Sand', value: '22', aliases: ['sand', 'ebbe sand'], footballerId: 'Sand, Ebbe'},
    ],
  },
  // ── Titles, records and club legends ─────────────────────────────────────
  {
    id: 'cl-titles-clubs',
    entries: [
      {rank: 1, name: 'Real Madrid', value: '15', aliases: ['real madrid', 'real', 'madrid']},
      {rank: 2, name: 'AC Milan', value: '7', aliases: ['milan', 'ac milan']},
      {rank: 3, name: 'Bayern Munich', value: '6', aliases: ['bayern', 'bayern munich', 'bayern munchen', 'fc bayern']},
      {rank: 4, name: 'Liverpool', value: '6', aliases: ['liverpool', 'lfc']},
      {rank: 5, name: 'Barcelona', value: '5', aliases: ['barcelona', 'barca', 'fc barcelona']},
      {rank: 6, name: 'Ajax', value: '4', aliases: ['ajax', 'ajax amsterdam']},
      {rank: 7, name: 'Inter', value: '3', aliases: ['inter', 'inter milan', 'internazionale']},
      {rank: 8, name: 'Manchester United', value: '3', aliases: ['man united', 'manchester united', 'united', 'man utd']},
      {rank: 9, name: 'Paris Saint-Germain', value: '2', aliases: ['psg', 'paris saint-germain', 'paris saint germain', 'paris sg', 'paris']},
      {rank: 10, name: 'Chelsea', value: '2', aliases: ['chelsea']},
    ],
  },
  {
    id: 'english-titles-clubs',
    entries: [
      {rank: 1, name: 'Liverpool', value: '20', aliases: ['liverpool', 'lfc']},
      {rank: 2, name: 'Manchester United', value: '20', aliases: ['man united', 'manchester united', 'united', 'man utd']},
      {rank: 3, name: 'Arsenal', value: '14', aliases: ['arsenal']},
      {rank: 4, name: 'Manchester City', value: '10', aliases: ['man city', 'manchester city', 'city']},
      {rank: 5, name: 'Everton', value: '9', aliases: ['everton']},
      {rank: 6, name: 'Aston Villa', value: '7', aliases: ['aston villa', 'villa']},
      {rank: 7, name: 'Sunderland', value: '6', aliases: ['sunderland']},
      {rank: 8, name: 'Chelsea', value: '6', aliases: ['chelsea']},
      {rank: 9, name: 'Newcastle United', value: '4', aliases: ['newcastle', 'newcastle united']},
      {rank: 10, name: 'Sheffield Wednesday', value: '4', aliases: ['sheffield wednesday', 'wednesday']},
    ],
  },
  {
    id: 'serie-a-titles-clubs',
    entries: [
      {rank: 1, name: 'Juventus', value: '36', aliases: ['juventus', 'juve']},
      {rank: 2, name: 'Inter', value: '21', aliases: ['inter', 'inter milan', 'internazionale']},
      {rank: 3, name: 'AC Milan', value: '19', aliases: ['milan', 'ac milan']},
      {rank: 4, name: 'Genoa', value: '9', aliases: ['genoa']},
      {rank: 5, name: 'Torino', value: '7', aliases: ['torino']},
      {rank: 6, name: 'Bologna', value: '7', aliases: ['bologna']},
      {rank: 7, name: 'Pro Vercelli', value: '7', aliases: ['pro vercelli', 'vercelli']},
      {rank: 8, name: 'Napoli', value: '4', aliases: ['napoli']},
      {rank: 9, name: 'Roma', value: '3', aliases: ['roma', 'as roma']},
      {rank: 10, name: 'Lazio', value: '2', aliases: ['lazio']},
    ],
  },
  {
    id: 'german-titles-clubs',
    entries: [
      {rank: 1, name: 'Bayern Munich', value: '35', aliases: ['bayern', 'bayern munich', 'bayern munchen', 'fc bayern']},
      {rank: 2, name: '1. FC Nürnberg', value: '9', aliases: ['nurnberg', 'nuremberg', 'fc nurnberg', '1. fc nurnberg']},
      {rank: 3, name: 'Borussia Dortmund', value: '8', aliases: ['dortmund', 'borussia dortmund', 'bvb']},
      {rank: 4, name: 'Schalke 04', value: '7', aliases: ['schalke', 'schalke 04']},
      {rank: 5, name: 'Hamburger SV', value: '6', aliases: ['hamburg', 'hamburger sv', 'hsv']},
      {rank: 6, name: 'VfB Stuttgart', value: '5', aliases: ['stuttgart', 'vfb stuttgart']},
      {rank: 7, name: 'Borussia Mönchengladbach', value: '5', aliases: ['gladbach', 'monchengladbach', 'borussia monchengladbach']},
      {rank: 8, name: 'Werder Bremen', value: '4', aliases: ['werder', 'werder bremen', 'bremen']},
      {rank: 9, name: '1. FC Kaiserslautern', value: '4', aliases: ['kaiserslautern', '1. fc kaiserslautern', 'lautern']},
      {rank: 10, name: '1. FC Köln', value: '3', aliases: ['koln', 'fc koln', '1. fc koln', 'cologne']},
    ],
  },
  {
    id: 'fa-cups-clubs',
    entries: [
      {rank: 1, name: 'Arsenal', value: '14', aliases: ['arsenal']},
      {rank: 2, name: 'Manchester United', value: '13', aliases: ['man united', 'manchester united', 'united', 'man utd']},
      {rank: 3, name: 'Manchester City', value: '8', aliases: ['man city', 'manchester city', 'city']},
      {rank: 4, name: 'Liverpool', value: '8', aliases: ['liverpool', 'lfc']},
      {rank: 5, name: 'Chelsea', value: '8', aliases: ['chelsea']},
      {rank: 6, name: 'Tottenham Hotspur', value: '8', aliases: ['tottenham', 'spurs', 'tottenham hotspur']},
      {rank: 7, name: 'Aston Villa', value: '7', aliases: ['aston villa', 'villa']},
      {rank: 8, name: 'Newcastle United', value: '6', aliases: ['newcastle', 'newcastle united']},
      {rank: 9, name: 'Blackburn Rovers', value: '6', aliases: ['blackburn', 'blackburn rovers']},
      {rank: 10, name: 'Everton', value: '5', aliases: ['everton']},
    ],
  },
  {
    id: 'euro-titles-nations',
    entries: [
      {rank: 1, name: 'Spain', value: '4', aliases: ['spain', 'spanien']},
      {rank: 2, name: 'Germany', value: '3', aliases: ['germany', 'tyskland', 'west germany', 'vesttyskland']},
      {rank: 3, name: 'Italy', value: '2', aliases: ['italy', 'italien']},
      {rank: 4, name: 'France', value: '2', aliases: ['france', 'frankrig']},
      {rank: 5, name: 'Portugal', value: '1', aliases: ['portugal']},
      {rank: 6, name: 'Greece', value: '1', aliases: ['greece', 'graekenland', 'grækenland']},
      {rank: 7, name: 'Denmark', value: '1', aliases: ['denmark', 'danmark']},
      {rank: 8, name: 'Netherlands', value: '1', aliases: ['netherlands', 'holland']},
      {rank: 9, name: 'Czechoslovakia', value: '1', aliases: ['czechoslovakia', 'tjekkoslovakiet']},
      {rank: 10, name: 'Soviet Union', value: '1', aliases: ['soviet union', 'ussr', 'sovjetunionen', 'sovjet']},
    ],
  },
  {
    id: 'pl-goals-season',
    entries: [
      {rank: 1, name: 'Erling Haaland', value: '36 (2022/23)', aliases: ['haaland', 'erling haaland'], footballerId: 'Haaland, Erling'},
      {rank: 2, name: 'Alan Shearer', value: '34 (1994/95)', aliases: ['shearer', 'alan shearer'], footballerId: 'Shearer, Alan'},
      {rank: 3, name: 'Andy Cole', value: '34 (1993/94)', aliases: ['cole', 'andy cole', 'andrew cole'], footballerId: 'Cole, Andy'},
      {rank: 4, name: 'Mohamed Salah', value: '32 (2017/18)', aliases: ['salah', 'mohamed salah', 'mo salah'], footballerId: 'Salah, Mohamed'},
      {rank: 5, name: 'Luis Suárez', value: '31 (2013/14)', aliases: ['suarez', 'luis suarez'], footballerId: 'Suárez, Luis'},
      {rank: 6, name: 'Cristiano Ronaldo', value: '31 (2007/08)', aliases: ['cristiano ronaldo', 'cristiano', 'cr7', 'ronaldo'], footballerId: 'Ronaldo, Cristiano'},
      {rank: 7, name: 'Harry Kane', value: '30 (2017/18)', aliases: ['kane', 'harry kane'], footballerId: 'Kane, Harry'},
      {rank: 8, name: 'Thierry Henry', value: '30 (2003/04)', aliases: ['henry', 'thierry henry'], footballerId: 'Henry, Thierry'},
      {rank: 9, name: 'Robin van Persie', value: '30 (2011/12)', aliases: ['van persie', 'robin van persie', 'rvp'], footballerId: 'van Persie, Robin'},
      {rank: 10, name: 'Kevin Phillips', value: '30 (1999/00)', aliases: ['phillips', 'kevin phillips'], footballerId: 'Phillips, Kevin'},
    ],
  },
  {
    id: 'wc-goals-tournament',
    entries: [
      {rank: 1, name: 'Just Fontaine', value: '13 (1958)', aliases: ['fontaine', 'just fontaine'], footballerId: 'Fontaine, Just'},
      {rank: 2, name: 'Sándor Kocsis', value: '11 (1954)', aliases: ['kocsis', 'sandor kocsis'], footballerId: 'Kocsis, Sándor'},
      {rank: 3, name: 'Gerd Müller', value: '10 (1970)', aliases: ['gerd muller', 'gerd mueller', 'gerd', 'der bomber'], footballerId: 'Müller, Gerd'},
      {rank: 4, name: 'Eusébio', value: '9 (1966)', aliases: ['eusebio'], footballerId: 'Eusébio'},
      {rank: 5, name: 'Kylian Mbappé', value: '8 (2022)', aliases: ['mbappe', 'kylian mbappe'], footballerId: 'Mbappé, Kylian'},
      {rank: 6, name: 'Ronaldo Nazário', value: '8 (2002)', aliases: ['ronaldo', 'ronaldo nazario', 'r9', 'il fenomeno', 'el fenomeno'], footballerId: 'Ronaldo'},
      {rank: 7, name: 'Ademir', value: '8 (1950)', aliases: ['ademir'], footballerId: 'Ademir'},
      {rank: 8, name: 'Guillermo Stábile', value: '8 (1930)', aliases: ['stabile', 'guillermo stabile'], footballerId: 'Stábile, Guillermo'},
      {rank: 9, name: 'Jairzinho', value: '7 (1970)', aliases: ['jairzinho'], footballerId: 'Jairzinho'},
      {rank: 10, name: 'Grzegorz Lato', value: '7 (1974)', aliases: ['lato', 'grzegorz lato']},
    ],
  },
  {
    id: 'man-united-top-scorers',
    entries: [
      {rank: 1, name: 'Wayne Rooney', value: '253', aliases: ['rooney', 'wayne rooney'], footballerId: 'Rooney, Wayne'},
      {rank: 2, name: 'Bobby Charlton', value: '249', aliases: ['charlton', 'bobby charlton'], footballerId: 'Charlton, Bobby'},
      {rank: 3, name: 'Denis Law', value: '237', aliases: ['law', 'denis law'], footballerId: 'Law, Denis'},
      {rank: 4, name: 'Jack Rowley', value: '211', aliases: ['rowley', 'jack rowley'], footballerId: 'Rowley, Jack'},
      {rank: 5, name: 'Dennis Viollet', value: '179', aliases: ['viollet', 'dennis viollet'], footballerId: 'Viollet, Dennis'},
      {rank: 6, name: 'George Best', value: '179', aliases: ['best', 'george best'], footballerId: 'Best, George'},
      {rank: 7, name: 'Joe Spence', value: '168', aliases: ['spence', 'joe spence'], footballerId: 'Spence, Joe'},
      {rank: 8, name: 'Ryan Giggs', value: '168', aliases: ['giggs', 'ryan giggs'], footballerId: 'Giggs, Ryan'},
      {rank: 9, name: 'Mark Hughes', value: '163', aliases: ['mark hughes', 'hughes'], footballerId: 'Hughes, Mark'},
      {rank: 10, name: 'Ruud van Nistelrooy', value: '150', aliases: ['van nistelrooy', 'nistelrooy', 'ruud van nistelrooy', 'ruud'], footballerId: 'van Nistelrooy, Ruud'},
    ],
  },
  {
    id: 'liverpool-top-scorers',
    entries: [
      {rank: 1, name: 'Ian Rush', value: '346', aliases: ['rush', 'ian rush'], footballerId: 'Rush, Ian'},
      {rank: 2, name: 'Roger Hunt', value: '285', aliases: ['hunt', 'roger hunt'], footballerId: 'Hunt, Roger'},
      {rank: 3, name: 'Mohamed Salah', value: '245+', aliases: ['salah', 'mohamed salah', 'mo salah'], footballerId: 'Salah, Mohamed'},
      {rank: 4, name: 'Gordon Hodgson', value: '241', aliases: ['hodgson', 'gordon hodgson'], footballerId: 'Hodgson, Gordon'},
      {rank: 5, name: 'Billy Liddell', value: '228', aliases: ['liddell', 'billy liddell'], footballerId: 'Liddell, Billy'},
      {rank: 6, name: 'Steven Gerrard', value: '186', aliases: ['gerrard', 'steven gerrard', 'stevie g'], footballerId: 'Gerrard, Steven'},
      {rank: 7, name: 'Robbie Fowler', value: '183', aliases: ['fowler', 'robbie fowler'], footballerId: 'Fowler, Robbie'},
      {rank: 8, name: 'Kenny Dalglish', value: '172', aliases: ['dalglish', 'kenny dalglish', 'king kenny'], footballerId: 'Dalglish, Kenny'},
      {rank: 9, name: 'Michael Owen', value: '158', aliases: ['owen', 'michael owen'], footballerId: 'Owen, Michael'},
      {rank: 10, name: 'Harry Chambers', value: '151', aliases: ['chambers', 'harry chambers'], footballerId: 'Chambers, Harry'},
    ],
  },
  {
    id: 'real-madrid-top-scorers',
    entries: [
      {rank: 1, name: 'Cristiano Ronaldo', value: '450', aliases: ['cristiano ronaldo', 'cristiano', 'cr7', 'ronaldo'], footballerId: 'Ronaldo, Cristiano'},
      {rank: 2, name: 'Karim Benzema', value: '354', aliases: ['benzema', 'karim benzema'], footballerId: 'Benzema, Karim'},
      {rank: 3, name: 'Raúl', value: '323', aliases: ['raul', 'raul gonzalez'], footballerId: 'Raúl'},
      {rank: 4, name: 'Alfredo Di Stéfano', value: '308', aliases: ['di stefano', 'alfredo di stefano', 'distefano'], footballerId: 'Di Stéfano, Alfredo'},
      {rank: 5, name: 'Carlos Santillana', value: '290', aliases: ['santillana', 'carlos santillana'], footballerId: 'Santillana, Carlos'},
      {rank: 6, name: 'Ferenc Puskás', value: '242', aliases: ['puskas', 'ferenc puskas'], footballerId: 'Puskás, Ferenc'},
      {rank: 7, name: 'Hugo Sánchez', value: '208', aliases: ['hugo sanchez', 'sanchez'], footballerId: 'Sánchez, Hugo'},
      {rank: 8, name: 'Paco Gento', value: '182', aliases: ['gento', 'paco gento', 'francisco gento'], footballerId: 'Gento, Paco'},
      {rank: 9, name: 'Emilio Butragueño', value: '171', aliases: ['butragueno', 'emilio butragueno', 'el buitre'], footballerId: 'Butragueño, Emilio'},
      {rank: 10, name: 'Amancio', value: '155', aliases: ['amancio', 'amancio amaro'], footballerId: 'Amancio'},
    ],
  },
  {
    id: 'arsenal-top-scorers',
    entries: [
      {rank: 1, name: 'Thierry Henry', value: '228', aliases: ['henry', 'thierry henry'], footballerId: 'Henry, Thierry'},
      {rank: 2, name: 'Ian Wright', value: '185', aliases: ['wright', 'ian wright'], footballerId: 'Wright, Ian'},
      {rank: 3, name: 'Cliff Bastin', value: '178', aliases: ['bastin', 'cliff bastin'], footballerId: 'Bastin, Cliff'},
      {rank: 4, name: 'John Radford', value: '149', aliases: ['radford', 'john radford'], footballerId: 'Radford, John'},
      {rank: 5, name: 'Jimmy Brain', value: '139', aliases: ['brain', 'jimmy brain'], footballerId: 'Brain, Jimmy'},
      {rank: 6, name: 'Ted Drake', value: '139', aliases: ['drake', 'ted drake'], footballerId: 'Drake, Ted'},
      {rank: 7, name: 'Doug Lishman', value: '137', aliases: ['lishman', 'doug lishman'], footballerId: 'Lishman, Doug'},
      {rank: 8, name: 'Robin van Persie', value: '132', aliases: ['van persie', 'robin van persie', 'rvp'], footballerId: 'van Persie, Robin'},
      {rank: 9, name: 'Joe Hulme', value: '125', aliases: ['hulme', 'joe hulme'], footballerId: 'Hulme, Joe'},
      {rank: 10, name: 'David Jack', value: '124', aliases: ['david jack', 'jack'], footballerId: 'Jack, David'},
    ],
  },
  {
    id: 'man-united-appearances',
    entries: [
      {rank: 1, name: 'Ryan Giggs', value: '963', aliases: ['giggs', 'ryan giggs'], footballerId: 'Giggs, Ryan'},
      {rank: 2, name: 'Bobby Charlton', value: '758', aliases: ['charlton', 'bobby charlton'], footballerId: 'Charlton, Bobby'},
      {rank: 3, name: 'Paul Scholes', value: '718', aliases: ['scholes', 'paul scholes'], footballerId: 'Scholes, Paul'},
      {rank: 4, name: 'Bill Foulkes', value: '688', aliases: ['foulkes', 'bill foulkes'], footballerId: 'Foulkes, Bill'},
      {rank: 5, name: 'Gary Neville', value: '602', aliases: ['gary neville', 'neville'], footballerId: 'Neville, Gary'},
      {rank: 6, name: 'Wayne Rooney', value: '559', aliases: ['rooney', 'wayne rooney'], footballerId: 'Rooney, Wayne'},
      {rank: 7, name: 'Alex Stepney', value: '539', aliases: ['stepney', 'alex stepney'], footballerId: 'Stepney, Alex'},
      {rank: 8, name: 'Tony Dunne', value: '535', aliases: ['tony dunne', 'dunne'], footballerId: 'Dunne, Tony'},
      {rank: 9, name: 'Denis Irwin', value: '529', aliases: ['irwin', 'denis irwin'], footballerId: 'Irwin, Denis'},
      {rank: 10, name: 'Joe Spence', value: '510', aliases: ['spence', 'joe spence'], footballerId: 'Spence, Joe'},
    ],
  },
  {
    id: 'liverpool-appearances',
    entries: [
      {rank: 1, name: 'Ian Callaghan', value: '857', aliases: ['callaghan', 'ian callaghan'], footballerId: 'Callaghan, Ian'},
      {rank: 2, name: 'Jamie Carragher', value: '737', aliases: ['carragher', 'jamie carragher'], footballerId: 'Carragher, Jamie'},
      {rank: 3, name: 'Steven Gerrard', value: '710', aliases: ['gerrard', 'steven gerrard', 'stevie g'], footballerId: 'Gerrard, Steven'},
      {rank: 4, name: 'Ray Clemence', value: '665', aliases: ['clemence', 'ray clemence'], footballerId: 'Clemence, Ray'},
      {rank: 5, name: 'Emlyn Hughes', value: '665', aliases: ['emlyn hughes', 'hughes'], footballerId: 'Hughes, Emlyn'},
      {rank: 6, name: 'Ian Rush', value: '660', aliases: ['rush', 'ian rush'], footballerId: 'Rush, Ian'},
      {rank: 7, name: 'Phil Neal', value: '650', aliases: ['neal', 'phil neal'], footballerId: 'Neal, Phil'},
      {rank: 8, name: 'Tommy Smith', value: '638', aliases: ['smith', 'tommy smith'], footballerId: 'Smith, Tommy'},
      {rank: 9, name: 'Bruce Grobbelaar', value: '628', aliases: ['grobbelaar', 'bruce grobbelaar'], footballerId: 'Grobbelaar, Bruce'},
      {rank: 10, name: 'Alan Hansen', value: '620', aliases: ['hansen', 'alan hansen'], footballerId: 'Hansen, Alan'},
    ],
  },
];

/**
 * The live list pool. Starts as the bundled lists; an OTA content pack
 * replaces the contents in place via store.hydrate() (new titles arrive
 * through the pack's i18n strings under the same ids).
 */
export const LIST_POOL: TenballList[] = [...BUNDLED_LISTS];

/** Look up a list in the live pool, e.g. to resolve a pinned day. */
export function getListById(id: string): TenballList | undefined {
  return LIST_POOL.find(l => l.id === id);
}
